### ISSUE TITLE
Implement Door/Wall graphics

### ISSUE THREAD

**Issue by mbkarle** [JasperShoe/2DPlatformer#5]
Walls are now implemented but they have yet to use the graphics. This is a somewhat significant task in that we need to be careful that the adoption of images does not mess with the colliders on the walls (which are already finnicky as it is). 

The other thing to keep in mind is the current door collision system, which results in the player being able to phase through the wall as long as they are a little bit overlapping the door. A possible solution to this would be when implementing the graphics to make the door graphic larger than the door hitbox.

**Comment by JasperShoe** [comment]
Making the door larger wouldn't work, because then the player would just assume the boundaries stretch as far as the edges of the graphical door. This would create the same exact problem as we currently have.
